### ISSUE TITLE
wav file "Permission denied." Bug?

### ISSUE THREAD

**Issue by AssassinsLament** [justUmen/ComfyUI-BjornulfNodes#3]
Love your nodes, but I haven't been able to run the "Paused. Resume or Stop?" node because  I get an error on the wav file. I have uninstalled and reinstalled your nodes, but it persists.  I'm not using the portable version of comfyui, so maybe that's the reason?

Any way I can fix that?

![chrome_mw9BEjBz84](https://github.com/user-attachments/assets/fa4a1dba-6115-4753-8838-5121ed3573bd)

**Comment by justUmen** [comment]
Hi thx for the report.
I've never tried comfyui on windows so I'm not sure.... It's weird path... Not my code.
Did you install pydub dependency ? pip install pydub

**Comment by justUmen** [comment]
So apparently it's a pydub incompatibility, windows doesn't allow it to make temporary files for processing audio. (Don't ask me why, I'm not a Microsoft person. :P)
It's just about playing an audio file (my 1 second bell), not sure why it's such an issue, but yeah i didn't expect windows not to allow to play a 1 second audio file.
I'll check for a workaround, I'll let you know. :)

**Comment by AssassinsLament** [comment]
Thank you,

**Comment by justUmen** [comment]
I added something just for windows while avoiding additional packages. Also added an option for randomised control. If you use comfyui manager, you can just click Update and create a new node. Let me know if it works for you.

**Comment by AssassinsLament** [comment]
Works fine now, thank you for your hard work!

**Comment by justUmen** [comment]
Thx for testing my stuff. I'll test them all on windows before the 1.0. 😆
