### ISSUE TITLE
(IMPORT FAILED) Bjornulf_custom_nodes

### ISSUE THREAD

**Issue by perritomojao** [justUmen/ComfyUI-BjornulfNodes#4]
Hi thank you for the great nodes.

I am having trouble installing in my local comfyui and i also tried in runpod following your link and instructions. 
I believe i installed all dependencies. 

Cannot import C:\Users\Admin\ComfyUI\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: No module named 'facenet_pytorch'

Cannot import C:\Users\Admin\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BjornulfNodes-main module for custom nodes: No module named 'pydub'

i am new to this. running windows 10. please let me know what i can send you to help troubleshoot.

**Comment by justUmen** [comment]
Hi there !!!
The error you are giving me are from your local machine, yes I can see windows.

If you use the `ComfyUI_windows_portable` stuff, you can install dependencies with a terminal : `.\python.exe -m pip install pydub ollama`

First you need to find this python_embedded python.exe, then you can right click or shift + right inside the folder in your file manager to open a terminal there.

This is where I have it, with the command you need :

H:\ComfyUI_windows_portable\python_embeded> .\python.exe -m pip install pydub ollama

When you have to install something you can retake the same code and install the dependency you want :

like `.\python.exe -m pip install whateveryouwant`

If you need help with Runpod that's totally different, let me know. :)

**Comment by perritomojao** [comment]
OMG!!! thank you so much. I cant believe how easy it was. I found my \python_embeded folder. Then opened terminal inside this folder.  .\python.exe -m pip install pydub. this fixed my issue. Thank you so much again. Keep up the great work.

**Comment by justUmen** [comment]
Thank you too. 👍 
I will add more details about your problems in the README. 
More people might have similar issues.
